# Base image for WebSocket server
FROM node:16-alpine

WORKDIR /app

# Copy dependencies and install
COPY websocket/package*.json ./
RUN npm install

# Copy the WebSocket server source code
COPY websocket/ .

# Expose WebSocket port
EXPOSE 6000

# Run the WebSocket server
CMD ["node", "server.js"]
